using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using V2_Genesis.Data;
using V2_Genesis.Models;
using V2_Genesis.Services.Interfaces;
using V2_Genesis.Services.Objection;

namespace V2_Genesis.Services.Implementations;

public class ObjectionFormService : IObjectionFormService
{
    private readonly ApplicationDbContext _db;
    private readonly ObjectionRollSettings _rollSettings;

    public ObjectionFormService(
        ApplicationDbContext db,
        IOptions<ObjectionRollSettings> rollOpts)
    {
        _db = db;
        _rollSettings = rollOpts.Value;
    }

    public async Task<ObjectionSubmitResult> SubmitAsync(
        string rollSource, string userId, string appealStat, string? objAppeal,
        Obj_Property_InfoModel obj, Obj_Section1Model obj1,
        Obj_Section2Model obj2, Obj_Section3ResModel objR3,
        Obj_Section3BusModel objB3, Obj_Section3AgriModel objA3,
        Obj_Section4BusModel objB4, Obj_Section4ResModel objR4,
        Obj_Section5Model obj5, Obj_Section6Model obj6,
        Obj_Section7Model obj7, Obj_Files objFile,
        List<IFormFile> files, List<IFormFile> fileR,
        Obj_Property_Info_AppealModel appeal)
    {
        var cfg = _rollSettings.For(rollSource);
        bool isApp = appealStat == "True";
        bool isMulti = obj.Property_Type == "Multi";

        try
        {
            if (isApp)
                return await SubmitAppealAsync(cfg, userId, objAppeal,
                    obj, obj1, obj2, objR3, objB3, objA3, objB4, objR4,
                    obj5, obj6, obj7, objFile, files, fileR, appeal, isMulti);
            else
                return await SubmitObjectionAsync(cfg, userId,
                    obj, obj1, obj2, objR3, objB3, objA3, objB4, objR4,
                    obj5, obj6, obj7, objFile, files, fileR, isMulti);
        }
        catch (Exception ex)
        {
            return new ObjectionSubmitResult
            {
                Success = false,
                ErrorMessage = ex.Message
            };
        }
    }

    // ── OBJECTION ────────────────────────────────────────────────────
    private async Task<ObjectionSubmitResult> SubmitObjectionAsync(
        ObjectionRollEntry cfg, string userId,
        Obj_Property_InfoModel obj, Obj_Section1Model obj1,
        Obj_Section2Model obj2, Obj_Section3ResModel objR3,
        Obj_Section3BusModel objB3, Obj_Section3AgriModel objA3,
        Obj_Section4BusModel objB4, Obj_Section4ResModel objR4,
        Obj_Section5Model obj5, Obj_Section6Model obj6,
        Obj_Section7Model obj7, Obj_Files objFile,
        List<IFormFile> files, List<IFormFile> fileR, bool isMulti)
    {
        // 1. Property Info
        obj.PropertyFrom = cfg.ObjPrefix;
        obj.UserID = userId;
        obj.objection_Status = "Obj-Lodging";
        _db.Obj_Property_Info.Add(obj);
        await _db.SaveChangesAsync();

        string objRef = obj.Objection_No;  // generated by DB trigger
        int objId = (int)obj.Objection_ID;

        // 2. Sections 1–7
        SaveSection(obj1, objId, objRef, s => {
            s.Ref = objId; s.Objection_Ref_S1 = objRef;
        });
        _db.Obj_Section1.Add(obj1);

        SaveSection(obj2, objId, objRef, s => {
            s.Ref = objId;
            s.Objection_Ref_S2 = cfg.ObjPrefix + "-" + objId;
        });
        _db.Obj_Section2.Add(obj2);

        SetSectionRef(objA3, objId, cfg.ObjPrefix, "SA3",
            (s, r) => { s.Ref = objId; s.Objection_Ref_SA3 = r; });
        _db.Obj_Section3Agri.Add(objA3);

        SetSectionRef(objB3, objId, cfg.ObjPrefix, "SB3",
            (s, r) => { s.Ref = objId; s.Objection_Ref_SB3 = r; });
        _db.Obj_Section3Bus.Add(objB3);

        SetSectionRef(objR3, objId, cfg.ObjPrefix, "SR3",
            (s, r) => { s.Ref = objId; s.Objection_Ref_SR3 = r; });
        _db.Obj_Section3Res.Add(objR3);

        SetSectionRef(objB4, objId, cfg.ObjPrefix, "SB4",
            (s, r) => { s.Ref = objId; s.Objection_Ref_SB4 = r; });
        _db.Obj_Section4Bus.Add(objB4);

        SetSectionRef(objR4, objId, cfg.ObjPrefix, "SR4",
            (s, r) => { s.Ref = objId; s.Objection_Ref_SR4 = r; });
        _db.Obj_Section4Res.Add(objR4);

        SetSectionRef(obj5, objId, cfg.ObjPrefix, "S5",
            (s, r) => { s.Ref = objId; s.Objection_Ref_S5 = r; });
        _db.Obj_Section5.Add(obj5);

        SetSectionRef(obj6, objId, cfg.ObjPrefix, "S6",
            (s, r) => { s.Ref = objId; s.Objection_Ref_S6 = r; });
        _db.Obj_Section6.Add(obj6);

        obj7.Ref = objId;
        obj7.Objection_Ref_S7 = cfg.ObjPrefix + "-" + objId;
        obj7.RandomPin = GeneratePin();
        obj7.Section51Pin = GeneratePin();
        _db.Obj_Section7.Add(obj7);

        await _db.SaveChangesAsync();

        // 3. File upload
        int count = await SaveFilesAsync(cfg.FileRootPath, objRef, files, fileR, objFile);
        objFile.Ref = objId;
        objFile.Objection_Ref_files = cfg.ObjPrefix + "-" + objId;
        objFile.Evidence_count = count;
        _db.Obj_Files.Add(objFile);
        await _db.SaveChangesAsync();

        return new ObjectionSubmitResult
        {
            Success = true,
            ObjectionNo = objRef,
            Pin = obj7.RandomPin,
            IsMulti = isMulti,
            IsAppeal = false
        };
    }

    // ── APPEAL ───────────────────────────────────────────────────────
    private async Task<ObjectionSubmitResult> SubmitAppealAsync(
        ObjectionRollEntry cfg, string userId, string? objAppeal,
        Obj_Property_InfoModel obj, Obj_Section1Model obj1,
        Obj_Section2Model obj2, Obj_Section3ResModel objR3,
        Obj_Section3BusModel objB3, Obj_Section3AgriModel objA3,
        Obj_Section4BusModel objB4, Obj_Section4ResModel objR4,
        Obj_Section5Model obj5, Obj_Section6Model obj6,
        Obj_Section7Model obj7, Obj_Files objFile,
        List<IFormFile> files, List<IFormFile> fileR,
        Obj_Property_Info_AppealModel appeal, bool isMulti)
    {
        // 1. Appeal Info (first save to get Appeal_ID)
        appeal.A_UserID = userId;
        appeal.Appeal_Status = "App-Lodging";
        appeal.Obj_Ref = objAppeal;
        _db.Obj_Property_Info_Appeal.Add(appeal);
        await _db.SaveChangesAsync();

        string appNo = cfg.AppealPrefix + "-" + appeal.Appeal_ID;
        appeal.Appeal_No = appNo;
        appeal.Appeal_Type = obj.Objector_Type;
        appeal.A_Property_Type = obj.Property_Type;
        appeal.A_Property_Desc = obj.Property_Desc;
        appeal.A_Premise_id = obj.Premise_id;
        appeal.A_Unit_key = obj.Unit_key;
        appeal.A_Property_id = obj.Property_id;
        appeal.A_Valuation_Key = obj.Valuation_Key;
        appeal.A_Sector = obj.Sector;
        _db.Obj_Property_Info_Appeal.Update(appeal);
        await _db.SaveChangesAsync();

        int appId = (int)appeal.Appeal_ID;
      
        // 2. Sections
        obj1.Ref = appId; obj1.Appeal_Ref_S1 = appId; obj1.Objection_Ref_S1 = appNo;
        _db.Obj_Section1.Add(obj1);

        obj2.Ref = appId; obj2.Appeal_Ref_S2 = appId; obj2.Objection_Ref_S2 = appNo;
        _db.Obj_Section2.Add(obj2);

        objA3.Ref = appId; objA3.Appeal_Ref_SA3 = appId; objA3.Objection_Ref_SA3 = appNo;
        _db.Obj_Section3Agri.Add(objA3);

        objB3.Ref = appId; objB3.Appeal_Ref_SB3 = appId; objB3.Objection_Ref_SB3 = appNo;
        _db.Obj_Section3Bus.Add(objB3);

        objR3.Ref = appId; objR3.Appeal_Ref_SR3 = appId; objR3.Objection_Ref_SR3 = appNo;
        _db.Obj_Section3Res.Add(objR3);

        objB4.Ref = appId; objB4.Appeal_Ref_SB4 = appId; objB4.Objection_Ref_SB4 = appNo;
        _db.Obj_Section4Bus.Add(objB4);

        objR4.Ref = appId; objR4.Appeal_Ref_SR4 = appId; objR4.Objection_Ref_SR4 = appNo;
        _db.Obj_Section4Res.Add(objR4);

        obj5.Ref = appId; obj5.Appeal_Ref_S5 = appId; obj5.Objection_Ref_S5 = appNo;
        _db.Obj_Section5.Add(obj5);

        obj6.Ref = appId; obj6.Appeal_Ref_S6 = appId; obj6.Objection_Ref_S6 = appNo;
        _db.Obj_Section6.Add(obj6);

        obj7.Ref = appId; obj7.Appeal_Ref_S7 = appId; obj7.Objection_Ref_S7 = appNo;
        obj7.RandomPin = GeneratePin();
        obj7.Section51Pin = GeneratePin();
        _db.Obj_Section7.Add(obj7);

        await _db.SaveChangesAsync();

        // 3. Files
        int count = await SaveFilesAsync(cfg.FileRootPath, appNo, files, fileR, objFile);
        objFile.Ref = appId;
        objFile.Objection_Ref_files = appNo;
        objFile.Evidence_count = count;
        objFile.Appeal_Ref_files = 1;
        _db.Obj_Files.Add(objFile);
        await _db.SaveChangesAsync();

        return new ObjectionSubmitResult
        {
            Success = true,
            ObjectionNo = appNo,
            Pin = obj7.RandomPin,
            IsMulti = isMulti,
            IsAppeal = true
        };
    }

    // ── Helpers ───────────────────────────────────────────────────────
    private static string GeneratePin()
        => new Random().Next(100000, 999999).ToString();

    private static void SaveSection<T>(T s, int id, string refNo,
        Action<T> assign) => assign(s);

    private static void SetSectionRef<T>(T s, int id, string prefix,
        string suffix, Action<T, string> assign)
        => assign(s, prefix + "-" + id);

    private static async Task<int> SaveFilesAsync(
        string rootPath, string folder,
        List<IFormFile> files, List<IFormFile> fileR,
        Obj_Files objFile)
    {
        string dir = Path.Combine(rootPath, folder);
        Directory.CreateDirectory(dir);

        // Representative letter
        foreach (var f in fileR)
        {
            string repDir = Path.Combine(dir, "Representative Letter");
            Directory.CreateDirectory(repDir);
            string name = Path.GetFileName(f.FileName);
            await using var stream = File.Create(Path.Combine(repDir, name));
            await f.CopyToAsync(stream);
            objFile.Rep_letter = name;
        }

        // Evidence files
        int count = 0;
        foreach (var f in files)
        {
            count++;
            string name = Path.GetFileName(f.FileName);
            await using var stream = File.Create(Path.Combine(dir, name));
            await f.CopyToAsync(stream);
            SetFileSlot(objFile, count, name);
        }
        return count;
    }

    private static void SetFileSlot(Obj_Files f, int slot, string name)
    {
        switch (slot)
        {
            case 1: f.Files1 = name; break;
            case 2: f.Files2 = name; break;
            case 3: f.Files3 = name; break;
            case 4: f.Files4 = name; break;
            case 5: f.Files5 = name; break;
            case 6: f.Files6 = name; break;
            case 7: f.Files7 = name; break;
            case 8: f.Files8 = name; break;
            case 9: f.Files9 = name; break;
            case 10: f.Files10 = name; break;
        }
    }
}